from selenium.webdriver.common.by import By

class Buttons:
    LOGIN_BUTTON = (By.XPATH, "//a[@href='/account']")
    MODAL_CLOSE = (By.XPATH, "//button[contains(@class, 'Modal_modal__close')]")
    LOGIN = (By.XPATH, "//button[text()='Войти']")
    EYES = (By.CSS_SELECTOR, "div.input__icon.input__icon-action")
    REGISTR_BUTTON = (By.XPATH, "//button[text()='Зарегистрироваться']")
    UPDATE_BUTTON = (By.XPATH, "//button[text()='Восстановить']")
    EYES_FOCUSED = (By.XPATH, "//button[contains(@class, 'input__placeholder-focused')]")
    ORDER_HISTORY_BUTTON = (By.XPATH, "//a[@href='/account/order-history']")
    LOGOUT = (By.XPATH, "//button[text()='Выход']")
    BUN_BUTTON = (By.XPATH, "//span[text()='Булки']")
    SOUCE_BUTTON = (By.XPATH, "//span[text()='Соусы']")
    FILLING_BUTTON = (By.XPATH, "//span[text()='Начинки']")
    CONSTRUCTOR_PAGE = (By.XPATH, "//a[@href='/']")
    INGREDIENTS_BUTTON = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient')]")
    CREATE_ORDER = (By.XPATH, "//button[text()='Оформить заказ']")
    CLEAN_BUTTON = (By.CSS_SELECTOR, "div.App_App__aOmNj")
    ORDER_PAGE_BUTTON = (By.XPATH, "//a[@href='/feed']")
    FIRST_ORDER_IN_FEED = (By.XPATH,"(//*[contains(@class, 'OrderFeed_order')]//a[contains(@href, '/feed/')])[1]")

class Parameter:
    EMAIL = (By.XPATH, "//input[@name='name']")
    PASSWORD = (By.XPATH, "//input[@name='Пароль']")
    NAME = (By.XPATH, "//input[@name='name']")
    CODE = (By.XPATH, "//input[@name='name']")
    UPDATE_PASSWORD = (By.XPATH, "//input[@name='Введите новый пароль']")
    COUNTER = (By.CLASS_NAME, "counter_counter__ZNLkj")
    ORDER_NUMBER = (By.XPATH, "//h2[contains(@class, 'Modal_modal__title')]")
    USER_ORDER_HISTORY = (By.XPATH, "//div[contains(@class, 'OrderHistory_order')]")
    ORDER_DIGITS = (By.XPATH, ".//p[contains(@class, 'text_type_digits')]")
    FEED_FIRST_ORDER_NUMBER = (By.XPATH,"(//div[contains(@class, 'OrderFeed_list')]//p[contains(@class, 'text_type_digits')])[1]")
    HISTORY_LAST_ORDER_NUMBER = (By.XPATH,"(//div[contains(@class, 'OrderHistory_list')]//p[contains(@class, 'text_type_digits')])[1]")

class Links:
    REGISTR_USER = (By.XPATH, "//a[@href='/register']")
    UPDATE_PASSWORD = (By.XPATH, "//a[@href='/forgot-password']")
    LOGIN_LINK = (By.XPATH, "//a[@href='/login']")

class Pages:
    LOGIN_PAGE = (By.CLASS_NAME, "App_componentContainer__2JC2W")
    ORDER_PAGE = (By.CLASS_NAME, "Account_contentBox__2CPm3")
    MODAL_PAGE = (By.XPATH, "//div[contains(@class, 'Modal_modal__container')]")
    BURDER_CONSTRUCTOR_BUCKET = (By.XPATH, "//div[contains(@class, 'BurgerConstructor_basket')]")
    BURGER_MENU_PAGE = (By.XPATH, "//div[contains(@class, 'BurgerIngredients_ingredients__menuContainer')]")
    FEED_LIST = (By.XPATH, "//div[contains(@class, 'OrderFeed_list')]")
    FEED_ORDER_LIST = (By.XPATH, "//*[contains(@class, 'OrderFeed_orderList')]")
    FEED_ORDER = (By.XPATH, "//*[contains(@class, 'OrderFeed_order')]")
    FEED_IN_PROGRESS_ORDER = (By.XPATH,"//ul[contains(@class, 'OrderFeed_orderList__') and not(contains(@class, 'Ready'))]//li")
    ORDER_DETAIL = (By.XPATH,"//*[contains(@class, 'OrderDetails') or contains(@class, 'Modal_modal__container')]")
    ORDER_STATUS = (By.XPATH, "//ul[contains(@class, 'OrderFeed_orderListReady__')]")
    FEED_IN_PROGRESS_CONTAINER = (By.XPATH,"//ul[contains(@class, 'OrderFeed_orderList__') and not(contains(@class, 'Ready'))]")
    FEED_READY_CONTAINER = (By.XPATH, "//ul[contains(@class, 'OrderFeed_orderListReady__')]")
    FEED_ALL_CONTAINER = (By.XPATH,"//div[contains(@class, 'OrderFeed_number__') and contains(., 'Выполнено за все время')]")
    FEED_TODAY_CONTAINER = (By.XPATH,"//div[contains(@class, 'OrderFeed_number__') and contains(., 'Выполнено за сегодня')]")
    FEED_COUNTER_ALL = (By.XPATH, "(//p[contains(@class, 'OrderFeed_number__')])[1]")
    FEED_COUNTER_TODAY = (By.XPATH, "(//p[contains(@class, 'OrderFeed_number__')])[2]")
    ORDER_HISTORY_LINK = (By.CLASS_NAME, "OrderHistory_orderHistory__qy1VB")
    MODAL_ORDER = (By.XPATH, "//div[contains(@class, 'Modal_modal__container')]")
